server:
  port: 8601

keycloak:
  configurationFile: https://gitlab.int.corefiling.com/beacon/beacon/snippets/40/raw

licence.jar: https://svn-devenv.int.corefiling.com/svn/trunk/licences/cflInternal/internal.beacon.all.licence.jar

com.corefiling.labs.instanceServer: https://labs.cfl.io/instance-server