apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
