imageRegistry: artifacts.int.corefiling.com:5000

ingress:
  host: digit-frequency-analysis-service-tests.kube.int.corefiling.com

digit-frequency-analysis-service:
  pullPolicy: IfNotPresent
  keycloak:
    secretName: digit-frequency-analysis-service-keycloak
    resourceServer:
      clientId: integration-tests